### ISSUE TITLE
기본 기능 구현하기

### ISSUE THREAD

**Issue by simnalamburt** [simnalamburt/kumabot#1]
### TODO
- [x] 닉네임 표시
- [x] 카톡닉네임과 IRC 닉네임이 같을경우 IRC 노티가 계속 뜨는 문제 해결
- [x] 기존에 빕봇으로 연결되어있던애들 다 연결하기
- [ ] Join, Quit, nick 변경, ban 등도 중계하기
- [ ] 닉 API 만들기 (닉네임이 똑같으면 카톡으로 말하는 애들 구분이 안됨)
- [ ] 이모티콘
- [x] 사진
- [x] 샾검색
- [ ] etc
